# Generated by Django 5.2.5 on 2025-09-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.TextField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_modefied', models.DateField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adrees', models.TextField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=255)),
                ('ostan', models.CharField(choices=[('tehran', 'تهران'), ('gillan', 'گیلان'), ('alborz', 'البرز')], max_length=255)),
                ('zipcode', models.CharField(max_length=100)),
                ('hideusers', models.BooleanField(default=True)),
                ('comment', models.TextField()),
                ('postoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.blogpost')),
            ],
        ),
    ]
