# Generated by Django 5.2.5 on 2025-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
